version: '3'
services:
  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=thegogashvili
      - POSTGRES_PASSWORD=thegogashvili
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database

volumes:
  postgres_data:
